### PR TITLE
Add Review Expectations Section

### PR DESCRIPTION
**Pull request by lshep**

### CODE REVIEW

**Comment by lshep** [comment]
I'll have to add the link to the webpage of listed reviewers after I create it on Bioconductor.org 

I'm open to edits and revisions / renaming as you see fit.

**Review by kevinrue — COMMENTED** [review]
Overall, looks great, thanks for the contribution!

One question though, is whether that new section (of reviewer expectations) shows up where you would like it to, in terms of chapter order.

Right now, it shows after the References, and before the Appendix:

image

My thoughts:

- I would generally see References as the very last "regular" chapter.
- At the moment, the "regular" chapters are essentially about aspects of the reviewing process, which makes me wonder whether maybe we want to keep it that way, and push "meta" chapters (like Reviewer expectations) into the appendix.
- Johannes' latest contribution is a reviewer checklist Rmd file which is stored in the 'docs/' subdirectory and doesn't get rendered into the deployed book. This is a different use case from the Reviewers Expectations, which is something we clearly want to deploy in the book. I just mention it here to highlight different use cases that are possible.


## Conclusion

- Are you happy with the current location of the Reviewer Expectations?
- Would you agree to move it to the Appendix?
- Would you prefer to make it a 'regular' chapter before References? ( I think our separate discussion about unnumbered chapters would suggest 'no' to this question)

**Comment by lshep** [comment]
I'm not sure the best place for it and open to suggestions.  I felt like it didn't belong in a regular chapter since the package guideline package really can and should be advertised for developers to follow as well and they wouldn't care about review expectations.  

I thought about having it in the appendix but then I wasn't sure if that was too hidden? 

I think its okay for now and it might be more clear  as (if?) we move other developer guideline pages/thoughts over to the bookdown --  I feel like we should try to move as much as the development guidelines over as possible so things like suggested classes/import methods, and the similar pages currently on the main website should eventually be here ?  but maybe not ?

**Comment by lshep** [comment]
If you feel like it belongs in the appendix that's fine too.  I would have it before NEWS  and if possible un-number or unsubsectioned (like  A1 , A2, etc)

**Comment by lshep** [comment]
Actually --- If we had a different section -- like Appendix and called it Reviewer Resources -- we could display the expectations and Johannes checklist there?   There isn't anything that we wouldn't want exposed to the public so I don't see the harm in showing it -- but it should be different from the package guidelines --

**Comment by lshep** [comment]
I'm going to work on a new separate branch and possible pull request -- just for comparison but keep this in case we hate it ;)

**Comment by kevinrue** [comment]
Closing this PR deprecated by #3 and #4

**Pull request closed without merging**
