### PR TITLE
Reorganize

### PR DESCRIPTION
**Pull request by kevinrue**
Work continued from https://github.com/Bioconductor/pkgrevdocs/pull/3

### CODE REVIEW

**Comment by lshep** [comment]
I think it looks good.  Now we just need to figure out how to link Johannes checklist into the section for reviewer tools.

**Comment by kevinrue** [comment]
Then I guess the question becomes: do we want to compile and present the checklist Rmd as a chapter, or do we want to show the whole thing as one big code chunk (that reviewers would then copy paste to start their review) ?

**Comment by lshep** [comment]
I think I was thinking of just a link to the file that has the checklist but not necessarily display the entire checklist

**Comment by kevinrue** [comment]
OK, then I just need to force github action to copy the `docs` subdirectory to `gh-pages` so that it is deployed and can be linked as a web page. I guess. If it doesn't look good we can always change!

**Pull request merged**
