### PR TITLE
Check suggests only

### PR DESCRIPTION
**Pull request by jwokaty**

### CODE REVIEW

**Comment by jwokaty** [comment]
@hpages Do you think I need to add more details for troubleshooting and is the description of the set up sufficient to reproduce the errors?

**Comment by hpages** [comment]
Thanks Jen.

The list of `R CMD check` settings contained in this document and used by BBS:  https://github.com/Bioconductor/pkgrevdocs/blob/46318fbd697bba5e7e825123672d16c3037f7c8b/troubleshoot-build-report.Rmd#L40-L45
is out of date. The settings that are _effectively_ used are defined in the `Renviron.bioc` file [here](https://bioconductor.org/checkResults/devel/bioc-LATEST/Renviron.bioc), so I would recommed that this document points to that instead of repeating the list (DRY principle).

Note that the release and devel builds use their own `Renviron.bioc` file, which is not necessarily the same.

So I would  suggest adding the new `_R_CHECK_SUGGESTS_ONLY_=true` to https://github.com/Bioconductor/BBS/blob/devel/3.17/Renviron.bioc, with the following comment or something like that:
```
# _R_CHECK_SUGGESTS_ONLY_=true will allow 'R CMD check' to expose undeclared package dependencies.
# Note that:
# - The setting is effective **only** if base and recommended packages are installed in
#   <R_HOME>/library and all other packages are installed somewhere else (e.g. in
#   <R_HOME>/site-library). An easy way to achieve this setup is by creating the
#   <R_HOME>/site-library folder right after installing R and **before** installing any
#   package.
# - Only the Bioconductor **Linux** builders use the above setup at the moment (i.e. all
#   packages except base and recommended packages are installed in <R_HOME>/site-library).
#   This means that 'R CMD check' can only expose undeclared dependencies on the Bioconductor
#   Linux builders. It will NOT expose them on the Bioconductor Windows or Mac builders.
_R_CHECK_SUGGESTS_ONLY_=true
```

To make the need for this particular setup more prominant and help with reproducibility of the CHECK results on Linux, we could also edit the dotted box displayed at the beginning of each individual report. See for example the "To the developers/maintainers of the Biobase package:" box on [this report](https://bioconductor.org/checkResults/3.17/bioc-LATEST/Biobase/nebbiolo1-checksrc.html) (i.e. the box that is right below the title of the report "CHECK results for Biobase on nebbiolo1").


The SPB uses its own set of setting so `_R_CHECK_SUGGESTS_ONLY_=true` will also need to be set there.

H.

**Comment by jwokaty** [comment]
@hpages Is there a way we can point to the Renviron.bioc documents without having to change them with each release?

**Comment by jwokaty** [comment]
Nevermind. I see you're suggesting that we link to the ones published, not the ones in the repo.

**Comment by jwokaty** [comment]
@lshep Is this the right [Renviron](https://github.com/Bioconductor/packagebuilder/blob/python3/check.Renviron) for the spb?

**Comment by jwokaty** [comment]
Thanks for your review. I've added the links to the actual files that are published and removed the text. I've also edited https://github.com/Bioconductor/BBS/pull/249/files to add the setting and comment as you suggested.

**Comment by hpages** [comment]
Changes look good, thanks.

About https://github.com/Bioconductor/BBS/pull/249/files, I'm not convinced that we should add the  `_R_CHECK_SUGGESTS_ONLY_=true` setting to the 3.16 builds. I feel that it's late in the game for this and is probably not worth the effort and the extra frustration that this might cause to developers. At this point I'd rather have them focus on the 3.17 builds. That's just my feeling. What do @vjcitn @lshep think?

**Comment by jwokaty** [comment]
@hpages I agree about 3.16. I will remove them and make the corresponding edits, which I might save for next week :)

**Comment by lshep** [comment]
I also agree too late in the game for this on 3.16. With the freeze only 2 weeks away.

**Comment by lshep** [comment]
@jwokaty  can the conflicts be resolved so this can complete and be merged?

**Comment by jwokaty** [comment]
@lshep This is ready to merge. Please review.

**Comment by lshep** [comment]
Thanks

**Pull request merged**
